### ISSUE TITLE
CSS variables gets hardcoded

### ISSUE THREAD

**Issue by kodeFant** [jfbrennan/m-#139]
Hi!

I think there is a tiny problem with how the `m-` CSS is compiled and distributed.

It seems that instead of shipping with the CSS variables, it hardcodes thes usage of these values on compilation.

For example here it has replaced calling the variable with a hardcoded color:

![image](https://github.com/user-attachments/assets/574cab28-f9da-484d-9732-54bb10381602)

But the source apparently uses CSS variables:

![image](https://github.com/user-attachments/assets/8bc31152-05b5-4c07-a9c6-1d8fa14d7be7)

This makes theming difficult because we need to override the rules instead of the variables, which I suspect you didn't intend.

I will happily try to make a PR resolving it if this is interesting.

**Comment by craigrodway** [comment]
Hi! Just wondering if @jfbrennan would consider re-opening this issue (please? :)) and revisiting the build process? It would be great if the dist css used var() references instead of the hard-coded resolved values :) Thanks!

**Comment by jfbrennan** [comment]
Hey guys, thanks for the reaching out. 

First let me clarify this:
>It seems that instead of shipping with the CSS variables, it hardcodes thes usage of these values on compilation.

The published stylesheet does include Mdash's variables. You can see the `--m-*` custom properties under :root right at the top of the file https://unpkg.com/m-@3.2.0/dist/m-.css. They are included so your app's own CSS and JavaScript can use them.

However, in the interest of shipping the smallest file possible I have been using a PostCSS plugin for converting var() to the actual value. It saves some bytes. I didn't see it as a problem because I didn't envision people theming Mdash. Because the codebase is so simple I kind of assumed people would rather fork and modify as @kodeFant did, but there does seem to be some interest in theming.

So yes @craigrodway I am open to changing the build process and I actually back in June (https://github.com/jfbrennan/m-/commit/5678081bac1267daa935c3324179a3a3f063dd99#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519).

FYI I've been focused on a private fork for most of 2024. Will be bringing some of those goodies back to Mdash in a v4 release. That stylesheet will preserve instances of var(), which would effectively support theming.

**Comment by craigrodway** [comment]
Thanks for replying @jfbrennan, your reply and the context you've added is helpful and appreciated!

I did notice that the published version includes the variables, but customising _those_ doesn't affect the styles already present and used in `m-.css` itself.

The great thing about m- is that it is small enough and useful enough to just use the built assets as they are, without requiring a local build step at all.

Thanks again, and very much looking forward to v4! :)
